// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (ticket_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, ticket_id, author_id, body, created_at
`

type CreateCommentParams struct {
	TicketID int64       `json:"ticket_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TicketID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByTicketID = `-- name: ListCommentsByTicketID :many
SELECT id, ticket_id, author_id, body, created_at FROM comments
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTicketID(ctx context.Context, ticketID int64) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
