// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (ticket_id, type, payload, actor_id)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, type, payload, actor_id, created_at
`

type CreateTicketEventParams struct {
	TicketID int64       `json:"ticket_id"`
	Type     string      `json:"type"`
	Payload  []byte      `json:"payload"`
	ActorID  pgtype.UUID `json:"actor_id"`
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvent, error) {
	row := q.db.QueryRow(ctx, createTicketEvent,
		arg.TicketID,
		arg.Type,
		arg.Payload,
		arg.ActorID,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Type,
		&i.Payload,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT id, ticket_id, type, payload, actor_id, created_at FROM ticket_events
WHERE ticket_id = $1
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListTicketEventsParams struct {
	TicketID int64 `json:"ticket_id"`
	ID       int64 `json:"id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListTicketEvents(ctx context.Context, arg ListTicketEventsParams) ([]TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, arg.TicketID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketEvent
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Type,
			&i.Payload,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
