package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

var (
	ErrCommentBodyRequired = errors.New("comment body is required")
)

// Comment is the core domain entity for a ticket comment.

// NewComment is a factory function for creating a new, valid comment.
// The ID is no longer set here; it will be generated by the database.
func NewComment(ticketID int64, authorID uuid.UUID, body string) (*Comment, error) {
	if body == "" {
		return nil, ErrCommentBodyRequired
	}
	if authorID == uuid.Nil {
		return nil, errors.New("author ID is required")
	}
	if ticketID == 0 {
		return nil, errors.New("ticket ID is required")
	}

	return &Comment{
		TicketID:  ticketID,
		AuthorID:  authorID,
		Body:      body,
		CreatedAt: time.Now().UTC(),
	}, nil
}

// IsAuthoredBy checks if the comment was written by the given user
func (c *Comment) IsAuthoredBy(userID uuid.UUID) bool {
	return c.AuthorID == userID
}
