package domain

import (
	"time"

	"github.com/google/uuid"
	apperrors "github.com/lorrc/service-desk-backend/internal/core/errors"
)

const (
	MaxCommentBodyLength = 10000
)

// Comment is the core domain entity for a ticket comment.
type Comment struct {
	ID        uuid.UUID
	TicketID  int64
	AuthorID  uuid.UUID
	Body      string
	CreatedAt time.Time
}

// CommentParams holds parameters for creating a new comment
type CommentParams struct {
	TicketID int64
	AuthorID uuid.UUID
	Body     string
}

// Validate validates comment creation parameters
func (p *CommentParams) Validate() error {
	errs := apperrors.NewValidationErrors()

	if p.TicketID == 0 {
		errs.Add("ticketId", "Ticket ID is required")
	}

	if p.AuthorID == uuid.Nil {
		errs.Add("authorId", "Author ID is required")
	}

	if p.Body == "" {
		errs.Add("body", "Comment body is required")
	} else if len(p.Body) > MaxCommentBodyLength {
		errs.Add("body", "Comment body must be 10,000 characters or less")
	}

	if errs.HasErrors() {
		return errs
	}
	return nil
}

// NewComment is a factory function for creating a new, valid comment.
func NewComment(params CommentParams) (*Comment, error) {
	if err := params.Validate(); err != nil {
		return nil, err
	}

	return &Comment{
		// ID is generated by the database
		TicketID:  params.TicketID,
		AuthorID:  params.AuthorID,
		Body:      params.Body,
		CreatedAt: time.Now().UTC(),
	}, nil
}

// IsAuthoredBy checks if the comment was written by the given user
func (c *Comment) IsAuthoredBy(userID uuid.UUID) bool {
	return c.AuthorID == userID
}
