package postgres

import (
	"context"
	// ... imports
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/lorrc/service-desk-backend/internal/adapters/secondary/postgres/db"
	"github.com/lorrc/service-desk-backend/internal/core/domain"
	"github.com/lorrc/service-desk-backend/internal/core/ports"
)

type UserRepository struct {
	// db.Querier is the interface generated by sqlc
	q db.Querier
}

// Ensure interface satisfaction
var _ ports.UserRepository = (*UserRepository)(nil)

func NewUserRepository(pool *pgxpool.Pool) ports.UserRepository {
	return &UserRepository{
		q: db.New(pool),
	}
}

// Helper function for mapping DB model to Domain model
func mapDBUserToDomain(dbUser db.User) *domain.User {
	return &domain.User{
		ID:             dbUser.ID,
		OrganizationID: dbUser.OrganizationID,
		FullName:       dbUser.FullName,
		Email:          dbUser.Email,
		PasswordHash:   dbUser.PasswordHash,
		CreatedAt:      dbUser.CreatedAt.Time, // Handle TIMESTAMPTZ conversion
	}
}

func (r *UserRepository) Create(ctx context.Context, user *domain.User) (*domain.User, error) {
	// Map Domain -> DB Params
	params := db.CreateUserParams{
		// ... mapping fields ...
	}

	createdUser, err := r.q.CreateUser(ctx, params)
	if err != nil {
		// Handle database errors (e.g., unique constraint violations)
		return nil, err
	}

	return mapDBUserToDomain(createdUser), nil
}

// ... Implement GetByEmail ...
